- hosts: master
  become: yes
  tasks:

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: /home/{{ ansible_user }}
        creates: cluster_initialized.txt

    - name: create .kube directory
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"     

    - name: install pod network
      become_user: "{{ ansible_user }}"
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: /home/{{ ansible_user }}
        creates: pod_network_setup.txt